threads: 4
connection-pool: 1

spring:
  application:
    name: DB_Replication
  datasource:
    primary:
      url: jdbc:postgresql://db:5432/mydb
      username: admin
      password: admin
      maximum-pool-size: ${connection-pool}
    replica:
      url: jdbc:postgresql://db:5432/mydb
      username: admin
      password: admin
      maximum-pool-size: ${connection-pool}
  flyway:
    enabled: true
    url: ${spring.datasource.primary.url}
    user: ${spring.datasource.primary.username}
    password: ${spring.datasource.primary.password}

server:
  tomcat:
    max-threads: ${threads}
    min-spare-threads: ${threads}
    accept-count: 1000
